#  Dracula Pro Buffy
#  ┌─┐┬  ┌─┐┌─┐┬─┐┬┌┬┐┌┬┐┬ ┬
#  ├─┤│  ├─┤│  ├┬┘│ │  │ └┬┘
#  ┴ ┴┴─┘┴ ┴└─┘┴└─┴ ┴  ┴  ┴ 
#  urrick hunt

#[colors]
[colors.primary]
background = "#2A212C"           # &Background
foreground = "#F8F8F2"           # &Foreground
dim_foreground = "#C6C6C2"       # &AnsiColor27
bright_foreground = "#FFFFFF"    # &AnsiColor15

[colors.cursor]
text = "CellBackground"          # &Background
cursor = "#9F70A9"               # &Comment

[colors.vi_mode_cursor]
text = "CellBackground"          # &Background
cursor = "CellForeground"        # &Foreground

[colors.search.matches]
foreground = "#544158"           # &Selection
background = "#8AFF80"           # &AnsiColor2

[colors.search.focused_match]
foreground = "#544158"           # &Selection
background = "#FFCA80"           # &Orange

[colors.hints.start]
foreground = "#2A212C"           # &Background
background = "#FFFF80"           # &AnsiColor3

[colors.hints.end]
foreground = "#FFFF80"           # &AnsiColor3
background = "#2A212C"           # &Background

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#2A212C"           # &Background
background = "#9F70A9"           # &Comment

[colors.selection]
text = "CellForeground"          # &Foreground
background = "#544158"           # &Selection

[colors.normal]
black = "#2A212C"                # &AnsiColor0
red = "#FF9580"                  # &AnsiColor1
green = "#8AFF80"                # &AnsiColor2
yellow = "#FFFF80"               # &AnsiColor3
blue = "#9580FF"                 # &AnsiColor4
magenta = "#FF80BF"              # &AnsiColor5
cyan = "#80FFEA"                 # &AnsiColor6
white = "#F8F8F2"                # &AnsiColor7

[colors.bright]
black = "#624C67"                # &AnsiColor8
red = "#FFAA99"                  # &AnsiColor9
green = "#A2FF99"                # &AnsiColor10
yellow = "#FFFF99"               # &AnsiColor11
blue = "#AA99FF"                 # &AnsiColor12
magenta = "#FF99CC"              # &AnsiColor13
cyan = "#99FFEE"                 # &AnsiColor14
white = "#FFFFFF"                # &AnsiColor15

[colors.dim]
black = "#221A23"                # &AnsiColor20
red = "#CC7766"                  # &AnsiColor21
green = "#6ECC66"                # &AnsiColor22
yellow = "#CCCC66"               # &AnsiColor23
blue = "#7766CC"                 # &AnsiColor24
magenta = "#CC6699"              # &AnsiColor25
cyan = "#66CCBB"                 # &AnsiColor26
white = "#C6C6C2"                # &AnsiColor27

[[colors.indexed_colors]]
index = 16
color = "#FFCA80"                # &Orange

[[colors.indexed_colors]]
index = 17
color = "#E67070"                # &FunctionalRed
