[colors.bright]
black = "#7970A9"
blue = "#AA99FF"
cyan = "#99FFEE"
green = "#A2FF99"
magenta = "#FF99CC"
red = "#FFAA99"
white = "#FFFFFF"
yellow = "#FFFF99"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#22212C"
foreground = "#F8F8F2"

[colors.hints.end]
background = "#22212C"
foreground = "#FFFF80"

[colors.hints.start]
background = "#FFFF80"
foreground = "#22212C"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#7970A9"
blue = "#9580FF"
cyan = "#80FFEA"
green = "#8AFF80"
magenta = "#FF80BF"
red = "#FF9580"
white = "#F8F8F2"
yellow = "#FFFF80"

[colors.primary]
background = "#22212C"
bright_foreground = "#FFFFFF"
foreground = "#F8F8F2"

[colors.search.focused_match]
background = "#FFCA80"
foreground = "#454158"

[colors.search.matches]
background = "#8AFF80"
foreground = "#454158"

[colors.selection]
background = "#454158"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
