[tools]
go = "latest"
gradle = "latest"
java = "corretto-23.0.2.7.1"
just = "latest"
lua = "latest"
maven = "latest"
node = "latest"
python = "3.13.2"
ruff = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
