[tools]
black = "latest"
go = "latest"
gradle = "latest"
java = "corretto-25"
just = "latest"
lua = "latest"
maven = "latest"
node = "latest"
python = "3.14"
ruff = "latest"
rust = "latest"
usage = "latest"
uv = "latest"

[settings]
auto_update = true
