[general]
live_config_reload = true
import = [
 "./current_theme.toml"
]

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.dimensions]
columns = 150
lines = 30 

[window.padding]
x = 10
y = 10

[window]
option_as_alt = "OnlyLeft"

[cursor]
style = { shape = "Block", blinking = "Always" }

[keyboard]
bindings = [
  { key = "Left",   mods = "Alt", chars = "\u001BB"},
  { key = "Right",  mods = "Alt", chars = "\u001BF" } 
]

[env]
CROSSFONT_FALLBACK_FONTS = "Iosevka Nerd Font Mono"
