[general]
live_config_reload = true

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.dimensions]
columns = 150
lines = 30 

[window.padding]
x = 10
y = 10

[cursor]
style = { shape = "Block", blinking = "Always" }

